import type { Activity, Category, Mood } from "../../store/planStore";

export const CATEGORIES: Category[] = [
  "food",
  "outdoor",
  "entertainment",
  "learning",
  "fitness",
  "self-care",
];

export const MOODS: Mood[] = ["happy", "relaxed", "energetic", "chill"];

export const activitiesCatalog: Activity[] = [
  {
    id: "hiking",
    title: "Hiking Adventure",
    category: "outdoor",
    icon: "🏃",
    defaultDurationMin: 180,
    moods: ["energetic", "happy"],
  },
  {
    id: "brunch",
    title: "Weekend Brunch",
    category: "food",
    icon: "🍳",
    defaultDurationMin: 90,
    moods: ["relaxed", "happy"],
  },
  {
    id: "movie",
    title: "Watch a Movie",
    category: "entertainment",
    icon: "🎬",
    defaultDurationMin: 120,
    moods: ["relaxed", "chill"],
  },
  {
    id: "yoga",
    title: "Yoga Session",
    category: "fitness",
    icon: "🧘",
    defaultDurationMin: 60,
    moods: ["relaxed", "energetic"],
  },
  {
    id: "cooking",
    title: "Cook a New Recipe",
    category: "food",
    icon: "👨‍🍳",
    defaultDurationMin: 120,
    moods: ["happy", "chill"],
  },
  {
    id: "reading",
    title: "Reading Time",
    category: "self-care",
    icon: "📚",
    defaultDurationMin: 60,
    moods: ["relaxed", "chill"],
  },
  {
    id: "cycling",
    title: "Cycling",
    category: "outdoor",
    icon: "🚲",
    defaultDurationMin: 120,
    moods: ["energetic", "happy"],
  },
  {
    id: "gaming",
    title: "Video Games",
    category: "entertainment",
    icon: "🎮",
    defaultDurationMin: 120,
    moods: ["chill", "happy"],
  },
  {
    id: "meditation",
    title: "Meditation",
    category: "self-care",
    icon: "🧘‍♂️",
    defaultDurationMin: 30,
    moods: ["relaxed", "chill"],
  },
  {
    id: "workshop",
    title: "Online Workshop",
    category: "learning",
    icon: "💻",
    defaultDurationMin: 120,
    moods: ["energetic", "happy"],
  },
  {
    id: "picnic",
    title: "Park Picnic",
    category: "outdoor",
    icon: "🧺",
    defaultDurationMin: 150,
    moods: ["happy", "relaxed"],
  },
  {
    id: "museum",
    title: "Museum Visit",
    category: "learning",
    icon: "🏛️",
    defaultDurationMin: 180,
    moods: ["relaxed", "chill"],
  },
  {
    id: "gym",
    title: "Gym Workout",
    category: "fitness",
    icon: "💪",
    defaultDurationMin: 90,
    moods: ["energetic"],
  },
  {
    id: "spa",
    title: "Spa Treatment",
    category: "self-care",
    icon: "💆",
    defaultDurationMin: 120,
    moods: ["relaxed"],
  },
  {
    id: "gardening",
    title: "Gardening",
    category: "outdoor",
    icon: "🌱",
    defaultDurationMin: 120,
    moods: ["chill", "happy"],
  },
];
